[package]
name = "lt7683"
description = "LT7683 display driver"
repository = "https://github.com/LAMBDA-CORE-HEAVY-INDUSTRIES/LT7683"
license = "MIT"
keywords = ["lt7683", "rust-embedded", "lcd-display"]
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-hal = "1.0.0"
